import 'package:flutter/material.dart';

const Color kColorFormFieldsAuthPage = Color(0xFFE9E9E9);
const Color kColorHeadingsAuthPage = Colors.black87;
const Color kColorCursorAuthPage = Colors.black87;
const Color kColorInputFormFieldsAuthPage = Colors.black87;
const Color kColorErrorFormFieldsAuthPage = Colors.black54;
const Color kColorHintTextFormFieldsAuthPage = Color(0xFFB1B1B1);
const Color kColorButtonConfirmAuthPage = Color(0xFF444444);
const Color kColorTextSnackBarAuthPage = Color(0xFFE9E9E9);
const Color kColorTextConfirmButtonAuthPage = Colors.white;
const Color kColorTextGoogleButton = Colors.white;
const Color kColorGoogleButton = Color(0xFFEA4335);
const Color kColorErrorInvalidAuthPage = Colors.red;
const Color kColorAlreadyAUser = Colors.black87;
const Color kColorForgotPassAuthPage = Colors.black87;
const Color kColorAlreadySignInOptAuthPage = Colors.blue;
const Color kColorSnackBarBackgroundAuthPage = Colors.black87;
const Color kColorAlertDialogIconAuthPage = Colors.black87;
const Color kColorBackIconForgotPassPage = Colors.black87;
const Color kColorHomePageTitles = Colors.black87;
const Color kColorHomePageBg = Colors.white60;
const Color kColorWishlistPageBg = Colors.white60;
const Color kColorShoppingCartPageBg = Colors.white60;
const Color kColorProductTitleBg = Color(0xFFF6F6F6);
